[package]
name = "pallet-evm"
version = "6.0.0-dev"
authors = ["Parity Technologies <admin@parity.io>"]
edition = "2018"
license = "Apache-2.0"
homepage = "https://substrate.io"
repository = "https://github.com/paritytech/frontier/"
description = "FRAME EVM contracts pallet"
readme = "README.md"

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]

[dependencies]
serde = { version = "1.0.101", optional = true, features = ["derive"] }
codec = { package = "parity-scale-codec", version = "2.0.0", default-features = false }
scale-info = { version = "1.0.0", default-features = false, features = ["derive"] }
frame-support = { version = "4.0.0-dev", default-features = false, git = "https://github.com/webb-tools/substrate", branch = "erup-5" }
frame-system = { version = "4.0.0-dev", default-features = false, git = "https://github.com/webb-tools/substrate", branch = "erup-5" }
pallet-timestamp = { version = "4.0.0-dev", default-features = false, git = "https://github.com/webb-tools/substrate", branch = "erup-5" }
pallet-balances = { version = "4.0.0-dev", default-features = false, git = "https://github.com/webb-tools/substrate", branch = "erup-5" }
sp-core = { version = "4.0.0-dev", default-features = false, git = "https://github.com/webb-tools/substrate", branch = "erup-5" }
sp-runtime = { version = "4.0.0-dev", default-features = false, git = "https://github.com/webb-tools/substrate", branch = "erup-5" }
sp-std = { version = "4.0.0-dev", default-features = false, git = "https://github.com/webb-tools/substrate", branch = "erup-5" }
sp-io = { version = "4.0.0-dev", default-features = false, git = "https://github.com/webb-tools/substrate", branch = "erup-5" }
frame-benchmarking = { version = "4.0.0-dev", git = "https://github.com/webb-tools/substrate", branch = "erup-5", default-features = false, optional = true }
fp-evm = { version = "3.0.0-dev", default-features = false, path = "../../primitives/evm" }
primitive-types = { version = "0.10.0", default-features = false, features = ["rlp", "byteorder"] }
rlp = { version = "0.5", default-features = false }
evm = { version = "0.33.0", default-features = false, features = ["with-codec"] }
evm-runtime = { version = "0.33.0", default-features = false }
evm-gasometer = { version = "0.33.0", default-features = false }
sha3 = { version = "0.8", default-features = false }
log = { version = "0.4", default-features = false }
hex = { version = "0.4", default-features = false }

pallet-evm-precompile-simple = { default-features = false, path = "./precompile/simple" }
pallet-evm-precompile-sha3fips = { default-features = false, path = "./precompile/sha3fips" }
pallet-evm-precompile-modexp = { default-features = false, path = "./precompile/modexp" }
lazy_static = { version = "1.4.0", features = ["spin_no_std"] }

[features]
default = ["std"]
std = [
	"serde",
	"codec/std",
	"scale-info/std",
	"sp-core/std",
	"sp-runtime/std",
	"frame-support/std",
	"frame-system/std",
	"pallet-balances/std",
	"sp-io/std",
	"frame-benchmarking/std",
	"sp-std/std",
	"fp-evm/std",
	"sha3/std",
	"rlp/std",
	"primitive-types/std",
	"evm/std",
	"evm/with-serde",
	"evm-runtime/std",
	"evm-gasometer/std",
	"pallet-timestamp/std",
	"log/std",
	"hex/std",
	"pallet-evm-precompile-simple/std",
	"pallet-evm-precompile-sha3fips/std",
	"pallet-evm-precompile-modexp/std",
]
runtime-benchmarks = [
	"frame-benchmarking",
]
